language: node_js
threadsafe: yes
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
deploy:
  provider: heroku
  api_key:
    secure: OButxbVwz+qS5LB5VEnw6rbZ5vxRnhv23yK1/NQbQ4unLC5VwdRb93YQScevwK51jitt48HlfZHyU96w8QQExGK67W/08kwBpCvowXD9XE6oQG+4tcNZzOXWGKh8Au0DG9O5V5BaEUyySNsONIzuI7XmZ7d8eeHo4KatrraGyIk=
  skip_cleanup: true
  app: miui-ui
  on:
    repo: mindfreakthemon/miui-ui
