language: node_js
threadsafe: true
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
deploy:
  provider: heroku
  api_key:
    secure: eQlJqVK+vahFoS2DUmmNXyjxGZbU93uxYwV7sz1W3BcRWYa7J2LA+JkymFpj9lXJDBGMSy75BWryanhI1ZuAdTLxWYtLGXscAB/U5xp42RJG/ENAiPZ/crXAj2XkvoLLAOsXV8qeCU7Gus4W7QCw42V+Ca9SOg5U8digdcIhXW8=
  app: miui-ui
  on:
    repo: mindfreakthemon/miui-ui
